var hierarchy =
[
    [ "SignalWire\\Relay\\Action", "classSignalWire_1_1Relay_1_1Action.html", [
      [ "SignalWire\\Relay\\AIAction", "classSignalWire_1_1Relay_1_1AIAction.html", null ],
      [ "SignalWire\\Relay\\CollectAction", "classSignalWire_1_1Relay_1_1CollectAction.html", null ],
      [ "SignalWire\\Relay\\DetectAction", "classSignalWire_1_1Relay_1_1DetectAction.html", null ],
      [ "SignalWire\\Relay\\FaxAction", "classSignalWire_1_1Relay_1_1FaxAction.html", null ],
      [ "SignalWire\\Relay\\PayAction", "classSignalWire_1_1Relay_1_1PayAction.html", null ],
      [ "SignalWire\\Relay\\PlayAction", "classSignalWire_1_1Relay_1_1PlayAction.html", null ],
      [ "SignalWire\\Relay\\RecordAction", "classSignalWire_1_1Relay_1_1RecordAction.html", null ],
      [ "SignalWire\\Relay\\StreamAction", "classSignalWire_1_1Relay_1_1StreamAction.html", null ],
      [ "SignalWire\\Relay\\TapAction", "classSignalWire_1_1Relay_1_1TapAction.html", null ],
      [ "SignalWire\\Relay\\TranscribeAction", "classSignalWire_1_1Relay_1_1TranscribeAction.html", null ]
    ] ],
    [ "SignalWire\\Serverless\\Adapter", "classSignalWire_1_1Serverless_1_1Adapter.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Addresses", "classSignalWire_1_1REST_1_1Namespaces_1_1Addresses.html", null ],
    [ "SignalWire\\Server\\AgentServer", "classSignalWire_1_1Server_1_1AgentServer.html", null ],
    [ "SignalWire\\REST\\BaseResource", "classSignalWire_1_1REST_1_1BaseResource.html", [
      [ "SignalWire\\REST\\CrudResource", "classSignalWire_1_1REST_1_1CrudResource.html", [
        [ "SignalWire\\REST\\CrudWithAddresses", "classSignalWire_1_1REST_1_1CrudWithAddresses.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatApplications", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatApplications.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatCalls", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatCalls.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatFaxes", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatFaxes.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatLamlBins", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatLamlBins.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatMessages", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatMessages.html", null ],
        [ "SignalWire\\REST\\Namespaces\\CompatQueues", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatQueues.html", null ],
        [ "SignalWire\\REST\\Namespaces\\DatasphereDocuments", "classSignalWire_1_1REST_1_1Namespaces_1_1DatasphereDocuments.html", null ],
        [ "SignalWire\\REST\\Namespaces\\FabricCallFlows", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricCallFlows.html", null ],
        [ "SignalWire\\REST\\Namespaces\\FabricConferenceRooms", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricConferenceRooms.html", null ],
        [ "SignalWire\\REST\\Namespaces\\FabricCxmlApplications", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricCxmlApplications.html", null ],
        [ "SignalWire\\REST\\Namespaces\\FabricSubscribers", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricSubscribers.html", null ],
        [ "SignalWire\\REST\\Namespaces\\NumberGroups", "classSignalWire_1_1REST_1_1Namespaces_1_1NumberGroups.html", null ],
        [ "SignalWire\\REST\\Namespaces\\Queues", "classSignalWire_1_1REST_1_1Namespaces_1_1Queues.html", null ],
        [ "SignalWire\\REST\\Namespaces\\VideoConferences", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoConferences.html", null ],
        [ "SignalWire\\REST\\Namespaces\\VideoRooms", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoRooms.html", null ]
      ] ]
    ] ],
    [ "SignalWire\\Relay\\Call", "classSignalWire_1_1Relay_1_1Call.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Calling", "classSignalWire_1_1REST_1_1Namespaces_1_1Calling.html", null ],
    [ "SignalWire\\Relay\\Client", "classSignalWire_1_1Relay_1_1Client.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Compat", "classSignalWire_1_1REST_1_1Namespaces_1_1Compat.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatAccounts", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatAccounts.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatConferences", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatConferences.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatPhoneNumbers", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatPhoneNumbers.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatRecordings", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatRecordings.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatTokens", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatTokens.html", null ],
    [ "SignalWire\\REST\\Namespaces\\CompatTranscriptions", "classSignalWire_1_1REST_1_1Namespaces_1_1CompatTranscriptions.html", null ],
    [ "SignalWire\\REST\\Namespaces\\ConferenceLogs", "classSignalWire_1_1REST_1_1Namespaces_1_1ConferenceLogs.html", null ],
    [ "SignalWire\\Relay\\Constants", "classSignalWire_1_1Relay_1_1Constants.html", null ],
    [ "SignalWire\\Contexts\\Context", "classSignalWire_1_1Contexts_1_1Context.html", null ],
    [ "SignalWire\\Contexts\\ContextBuilder", "classSignalWire_1_1Contexts_1_1ContextBuilder.html", null ],
    [ "SignalWire\\DataMap\\DataMap", "classSignalWire_1_1DataMap_1_1DataMap.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Datasphere", "classSignalWire_1_1REST_1_1Namespaces_1_1Datasphere.html", null ],
    [ "SignalWire\\SWML\\Document", "classSignalWire_1_1SWML_1_1Document.html", null ],
    [ "SignalWire\\Relay\\Event", "classSignalWire_1_1Relay_1_1Event.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Fabric", "classSignalWire_1_1REST_1_1Namespaces_1_1Fabric.html", null ],
    [ "SignalWire\\REST\\Namespaces\\FabricAddresses", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricAddresses.html", null ],
    [ "SignalWire\\REST\\Namespaces\\FabricGenericResources", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricGenericResources.html", null ],
    [ "SignalWire\\REST\\Namespaces\\FabricTokens", "classSignalWire_1_1REST_1_1Namespaces_1_1FabricTokens.html", null ],
    [ "SignalWire\\REST\\Namespaces\\FaxLogs", "classSignalWire_1_1REST_1_1Namespaces_1_1FaxLogs.html", null ],
    [ "SignalWire\\SWAIG\\FunctionResult", "classSignalWire_1_1SWAIG_1_1FunctionResult.html", null ],
    [ "SignalWire\\Contexts\\GatherInfo", "classSignalWire_1_1Contexts_1_1GatherInfo.html", null ],
    [ "SignalWire\\Contexts\\GatherQuestion", "classSignalWire_1_1Contexts_1_1GatherQuestion.html", null ],
    [ "SignalWire\\REST\\HttpClient", "classSignalWire_1_1REST_1_1HttpClient.html", null ],
    [ "SignalWire\\Skills\\HttpHelper", "classSignalWire_1_1Skills_1_1HttpHelper.html", null ],
    [ "SignalWire\\REST\\Namespaces\\ImportedNumbers", "classSignalWire_1_1REST_1_1Namespaces_1_1ImportedNumbers.html", null ],
    [ "Iterator", null, [
      [ "SignalWire\\REST\\PaginatedIterator", "classSignalWire_1_1REST_1_1PaginatedIterator.html", null ]
    ] ],
    [ "SignalWire\\Logging\\Logger", "classSignalWire_1_1Logging_1_1Logger.html", null ],
    [ "SignalWire\\Logging\\LoggingConfig", "classSignalWire_1_1Logging_1_1LoggingConfig.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Logs", "classSignalWire_1_1REST_1_1Namespaces_1_1Logs.html", null ],
    [ "SignalWire\\Relay\\Message", "classSignalWire_1_1Relay_1_1Message.html", null ],
    [ "SignalWire\\REST\\Namespaces\\MessageLogs", "classSignalWire_1_1REST_1_1Namespaces_1_1MessageLogs.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Mfa", "classSignalWire_1_1REST_1_1Namespaces_1_1Mfa.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Project", "classSignalWire_1_1REST_1_1Namespaces_1_1Project.html", null ],
    [ "SignalWire\\REST\\Namespaces\\ProjectTokens", "classSignalWire_1_1REST_1_1Namespaces_1_1ProjectTokens.html", null ],
    [ "SignalWire\\POM\\PromptObjectModel", "classSignalWire_1_1POM_1_1PromptObjectModel.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Recordings", "classSignalWire_1_1REST_1_1Namespaces_1_1Recordings.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Registry", "classSignalWire_1_1REST_1_1Namespaces_1_1Registry.html", null ],
    [ "SignalWire\\REST\\Namespaces\\RegistryBrands", "classSignalWire_1_1REST_1_1Namespaces_1_1RegistryBrands.html", null ],
    [ "SignalWire\\REST\\Namespaces\\RegistryCampaigns", "classSignalWire_1_1REST_1_1Namespaces_1_1RegistryCampaigns.html", null ],
    [ "SignalWire\\REST\\Namespaces\\RegistryNumbers", "classSignalWire_1_1REST_1_1Namespaces_1_1RegistryNumbers.html", null ],
    [ "SignalWire\\REST\\Namespaces\\RegistryOrders", "classSignalWire_1_1REST_1_1Namespaces_1_1RegistryOrders.html", null ],
    [ "SignalWire\\REST\\RestClient", "classSignalWire_1_1REST_1_1RestClient.html", null ],
    [ "RuntimeException", null, [
      [ "SignalWire\\REST\\SignalWireRestError", "classSignalWire_1_1REST_1_1SignalWireRestError.html", null ],
      [ "SignalWire\\Relay\\RelayError", "classSignalWire_1_1Relay_1_1RelayError.html", null ],
      [ "SignalWire\\Utils\\SchemaValidationError", "classSignalWire_1_1Utils_1_1SchemaValidationError.html", null ]
    ] ],
    [ "SignalWire\\SWML\\Schema", "classSignalWire_1_1SWML_1_1Schema.html", null ],
    [ "SignalWire\\Utils\\SchemaUtils", "classSignalWire_1_1Utils_1_1SchemaUtils.html", null ],
    [ "SignalWire\\POM\\Section", "classSignalWire_1_1POM_1_1Section.html", null ],
    [ "SignalWire\\SWML\\Service", "classSignalWire_1_1SWML_1_1Service.html", [
      [ "SignalWire\\Agent\\AgentBase", "classSignalWire_1_1Agent_1_1AgentBase.html", [
        [ "SignalWire\\Prefabs\\ConciergeAgent", "classSignalWire_1_1Prefabs_1_1ConciergeAgent.html", null ],
        [ "SignalWire\\Prefabs\\FAQBotAgent", "classSignalWire_1_1Prefabs_1_1FAQBotAgent.html", null ],
        [ "SignalWire\\Prefabs\\InfoGathererAgent", "classSignalWire_1_1Prefabs_1_1InfoGathererAgent.html", null ],
        [ "SignalWire\\Prefabs\\ReceptionistAgent", "classSignalWire_1_1Prefabs_1_1ReceptionistAgent.html", null ],
        [ "SignalWire\\Prefabs\\SurveyAgent", "classSignalWire_1_1Prefabs_1_1SurveyAgent.html", null ]
      ] ]
    ] ],
    [ "SignalWire\\Security\\SessionManager", "classSignalWire_1_1Security_1_1SessionManager.html", null ],
    [ "SignalWire\\REST\\Namespaces\\ShortCodes", "classSignalWire_1_1REST_1_1Namespaces_1_1ShortCodes.html", null ],
    [ "SignalWire\\SignalWire", "classSignalWire_1_1SignalWire.html", null ],
    [ "SignalWire\\REST\\Namespaces\\SipProfile", "classSignalWire_1_1REST_1_1Namespaces_1_1SipProfile.html", null ],
    [ "SignalWire\\Skills\\SkillBase", "classSignalWire_1_1Skills_1_1SkillBase.html", [
      [ "SignalWire\\Skills\\Builtin\\ApiNinjasTrivia", "classSignalWire_1_1Skills_1_1Builtin_1_1ApiNinjasTrivia.html", null ],
      [ "SignalWire\\Skills\\Builtin\\CustomSkills", "classSignalWire_1_1Skills_1_1Builtin_1_1CustomSkills.html", null ],
      [ "SignalWire\\Skills\\Builtin\\Datasphere", "classSignalWire_1_1Skills_1_1Builtin_1_1Datasphere.html", null ],
      [ "SignalWire\\Skills\\Builtin\\DatasphereServerless", "classSignalWire_1_1Skills_1_1Builtin_1_1DatasphereServerless.html", null ],
      [ "SignalWire\\Skills\\Builtin\\Datetime", "classSignalWire_1_1Skills_1_1Builtin_1_1Datetime.html", null ],
      [ "SignalWire\\Skills\\Builtin\\GoogleMaps", "classSignalWire_1_1Skills_1_1Builtin_1_1GoogleMaps.html", null ],
      [ "SignalWire\\Skills\\Builtin\\InfoGatherer", "classSignalWire_1_1Skills_1_1Builtin_1_1InfoGatherer.html", null ],
      [ "SignalWire\\Skills\\Builtin\\Joke", "classSignalWire_1_1Skills_1_1Builtin_1_1Joke.html", null ],
      [ "SignalWire\\Skills\\Builtin\\Math", "classSignalWire_1_1Skills_1_1Builtin_1_1Math.html", null ],
      [ "SignalWire\\Skills\\Builtin\\McpGateway", "classSignalWire_1_1Skills_1_1Builtin_1_1McpGateway.html", null ],
      [ "SignalWire\\Skills\\Builtin\\NativeVectorSearch", "classSignalWire_1_1Skills_1_1Builtin_1_1NativeVectorSearch.html", null ],
      [ "SignalWire\\Skills\\Builtin\\PlayBackgroundFile", "classSignalWire_1_1Skills_1_1Builtin_1_1PlayBackgroundFile.html", null ],
      [ "SignalWire\\Skills\\Builtin\\Spider", "classSignalWire_1_1Skills_1_1Builtin_1_1Spider.html", null ],
      [ "SignalWire\\Skills\\Builtin\\SwmlTransfer", "classSignalWire_1_1Skills_1_1Builtin_1_1SwmlTransfer.html", null ],
      [ "SignalWire\\Skills\\Builtin\\WeatherApi", "classSignalWire_1_1Skills_1_1Builtin_1_1WeatherApi.html", null ],
      [ "SignalWire\\Skills\\Builtin\\WebSearch", "classSignalWire_1_1Skills_1_1Builtin_1_1WebSearch.html", null ],
      [ "SignalWire\\Skills\\Builtin\\WikipediaSearch", "classSignalWire_1_1Skills_1_1Builtin_1_1WikipediaSearch.html", null ]
    ] ],
    [ "SignalWire\\Skills\\SkillManager", "classSignalWire_1_1Skills_1_1SkillManager.html", null ],
    [ "SignalWire\\Skills\\SkillRegistry", "classSignalWire_1_1Skills_1_1SkillRegistry.html", null ],
    [ "SignalWire\\Contexts\\Step", "classSignalWire_1_1Contexts_1_1Step.html", null ],
    [ "SignalWire\\Utils\\UrlValidator", "classSignalWire_1_1Utils_1_1UrlValidator.html", null ],
    [ "SignalWire\\REST\\Namespaces\\Video", "classSignalWire_1_1REST_1_1Namespaces_1_1Video.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VideoConferenceTokens", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoConferenceTokens.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VideoRoomRecordings", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoRoomRecordings.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VideoRoomSessions", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoRoomSessions.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VideoRoomTokens", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoRoomTokens.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VideoStreams", "classSignalWire_1_1REST_1_1Namespaces_1_1VideoStreams.html", null ],
    [ "SignalWire\\REST\\Namespaces\\VoiceLogs", "classSignalWire_1_1REST_1_1Namespaces_1_1VoiceLogs.html", null ],
    [ "SignalWire\\Security\\WebhookMiddleware", "classSignalWire_1_1Security_1_1WebhookMiddleware.html", null ],
    [ "SignalWire\\Security\\WebhookValidator", "classSignalWire_1_1Security_1_1WebhookValidator.html", null ],
    [ "SignalWire\\Relay\\WebSocket", "classSignalWire_1_1Relay_1_1WebSocket.html", null ]
];