var hierarchy =
[
    [ "signalwire::relay::Action", "classsignalwire_1_1relay_1_1Action.html", null ],
    [ "signalwire::server::AgentServer", "classsignalwire_1_1server_1_1AgentServer.html", null ],
    [ "signalwire::relay::Call", "classsignalwire_1_1relay_1_1Call.html", null ],
    [ "signalwire::rest::RestClient::PhoneNumbersNamespace::CallFlowOptions", "structsignalwire_1_1rest_1_1RestClient_1_1PhoneNumbersNamespace_1_1CallFlowOptions.html", null ],
    [ "signalwire::rest::RestClient::CallingNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1CallingNamespace.html", null ],
    [ "signalwire::rest::RestClient::ChatNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1ChatNamespace.html", null ],
    [ "signalwire::rest::RestClient::CompatAccounts", "structsignalwire_1_1rest_1_1RestClient_1_1CompatAccounts.html", null ],
    [ "signalwire::rest::RestClient::CompatConferences", "structsignalwire_1_1rest_1_1RestClient_1_1CompatConferences.html", null ],
    [ "signalwire::rest::RestClient::CompatNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1CompatNamespace.html", null ],
    [ "signalwire::rest::RestClient::CompatPhoneNumbers", "structsignalwire_1_1rest_1_1RestClient_1_1CompatPhoneNumbers.html", null ],
    [ "signalwire::rest::RestClient::CompatRecordings", "structsignalwire_1_1rest_1_1RestClient_1_1CompatRecordings.html", null ],
    [ "signalwire::rest::RestClient::CompatTokens", "structsignalwire_1_1rest_1_1RestClient_1_1CompatTokens.html", null ],
    [ "signalwire::rest::RestClient::CompatTranscriptions", "structsignalwire_1_1rest_1_1RestClient_1_1CompatTranscriptions.html", null ],
    [ "signalwire::contexts::Context", "classsignalwire_1_1contexts_1_1Context.html", null ],
    [ "signalwire::contexts::ContextBuilder", "classsignalwire_1_1contexts_1_1ContextBuilder.html", null ],
    [ "signalwire::rest::CrudResource", "classsignalwire_1_1rest_1_1CrudResource.html", [
      [ "signalwire::rest::RestClient::AddressesNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1AddressesNamespace.html", null ],
      [ "signalwire::rest::RestClient::CompatApplications", "structsignalwire_1_1rest_1_1RestClient_1_1CompatApplications.html", null ],
      [ "signalwire::rest::RestClient::CompatCalls", "structsignalwire_1_1rest_1_1RestClient_1_1CompatCalls.html", null ],
      [ "signalwire::rest::RestClient::CompatFaxes", "structsignalwire_1_1rest_1_1RestClient_1_1CompatFaxes.html", null ],
      [ "signalwire::rest::RestClient::CompatLamlBins", "structsignalwire_1_1rest_1_1RestClient_1_1CompatLamlBins.html", null ],
      [ "signalwire::rest::RestClient::CompatMessages", "structsignalwire_1_1rest_1_1RestClient_1_1CompatMessages.html", null ],
      [ "signalwire::rest::RestClient::CompatQueues", "structsignalwire_1_1rest_1_1RestClient_1_1CompatQueues.html", null ],
      [ "signalwire::rest::RestClient::DatasphereDocuments", "structsignalwire_1_1rest_1_1RestClient_1_1DatasphereDocuments.html", null ],
      [ "signalwire::rest::RestClient::FabricResource", "structsignalwire_1_1rest_1_1RestClient_1_1FabricResource.html", [
        [ "signalwire::rest::RestClient::FabricResourcePUT", "structsignalwire_1_1rest_1_1RestClient_1_1FabricResourcePUT.html", [
          [ "signalwire::rest::RestClient::FabricCallFlows", "structsignalwire_1_1rest_1_1RestClient_1_1FabricCallFlows.html", null ],
          [ "signalwire::rest::RestClient::FabricConferenceRooms", "structsignalwire_1_1rest_1_1RestClient_1_1FabricConferenceRooms.html", null ],
          [ "signalwire::rest::RestClient::FabricCxmlApplications", "structsignalwire_1_1rest_1_1RestClient_1_1FabricCxmlApplications.html", null ],
          [ "signalwire::rest::RestClient::FabricSubscribers", "structsignalwire_1_1rest_1_1RestClient_1_1FabricSubscribers.html", null ]
        ] ]
      ] ],
      [ "signalwire::rest::RestClient::ImportedNumbersNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1ImportedNumbersNamespace.html", null ],
      [ "signalwire::rest::RestClient::NumberGroupsNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1NumberGroupsNamespace.html", null ],
      [ "signalwire::rest::RestClient::PhoneNumbersNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1PhoneNumbersNamespace.html", null ],
      [ "signalwire::rest::RestClient::QueuesNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1QueuesNamespace.html", null ],
      [ "signalwire::rest::RestClient::RecordingsNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1RecordingsNamespace.html", null ],
      [ "signalwire::rest::RestClient::ShortCodesNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1ShortCodesNamespace.html", null ],
      [ "signalwire::rest::RestClient::SipProfileNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1SipProfileNamespace.html", null ],
      [ "signalwire::rest::RestClient::VerifiedCallersNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1VerifiedCallersNamespace.html", null ],
      [ "signalwire::rest::RestClient::VideoConferences", "structsignalwire_1_1rest_1_1RestClient_1_1VideoConferences.html", null ],
      [ "signalwire::rest::RestClient::VideoRooms", "structsignalwire_1_1rest_1_1RestClient_1_1VideoRooms.html", null ]
    ] ],
    [ "signalwire::rest::RestClient::PhoneNumbersNamespace::CxmlWebhookOptions", "structsignalwire_1_1rest_1_1RestClient_1_1PhoneNumbersNamespace_1_1CxmlWebhookOptions.html", null ],
    [ "signalwire::datamap::DataMap", "classsignalwire_1_1datamap_1_1DataMap.html", null ],
    [ "signalwire::rest::RestClient::DatasphereNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1DatasphereNamespace.html", null ],
    [ "signalwire::swml::Document", "classsignalwire_1_1swml_1_1Document.html", null ],
    [ "signalwire::rest::RestClient::FabricAddresses", "structsignalwire_1_1rest_1_1RestClient_1_1FabricAddresses.html", null ],
    [ "signalwire::rest::RestClient::FabricGenericResources", "structsignalwire_1_1rest_1_1RestClient_1_1FabricGenericResources.html", null ],
    [ "signalwire::rest::RestClient::FabricNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1FabricNamespace.html", null ],
    [ "signalwire::rest::RestClient::FabricTokens", "structsignalwire_1_1rest_1_1RestClient_1_1FabricTokens.html", null ],
    [ "signalwire::swaig::FunctionResult", "classsignalwire_1_1swaig_1_1FunctionResult.html", null ],
    [ "signalwire::contexts::GatherInfo", "classsignalwire_1_1contexts_1_1GatherInfo.html", null ],
    [ "signalwire::contexts::GatherQuestion", "classsignalwire_1_1contexts_1_1GatherQuestion.html", null ],
    [ "signalwire::rest::HttpClient", "classsignalwire_1_1rest_1_1HttpClient.html", null ],
    [ "signalwire::agent::LanguageConfig", "structsignalwire_1_1agent_1_1LanguageConfig.html", null ],
    [ "signalwire::Logger", "classsignalwire_1_1Logger.html", null ],
    [ "signalwire::logging::Logger", "classsignalwire_1_1logging_1_1Logger.html", null ],
    [ "signalwire::rest::RestClient::LogsConferences", "structsignalwire_1_1rest_1_1RestClient_1_1LogsConferences.html", null ],
    [ "signalwire::rest::RestClient::LogsFax", "structsignalwire_1_1rest_1_1RestClient_1_1LogsFax.html", null ],
    [ "signalwire::rest::RestClient::LogsMessages", "structsignalwire_1_1rest_1_1RestClient_1_1LogsMessages.html", null ],
    [ "signalwire::rest::RestClient::LogsNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1LogsNamespace.html", null ],
    [ "signalwire::rest::RestClient::LogsVoice", "structsignalwire_1_1rest_1_1RestClient_1_1LogsVoice.html", null ],
    [ "signalwire::rest::RestClient::LookupNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1LookupNamespace.html", null ],
    [ "signalwire::relay::Message", "structsignalwire_1_1relay_1_1Message.html", null ],
    [ "signalwire::rest::RestClient::MFANamespace", "structsignalwire_1_1rest_1_1RestClient_1_1MFANamespace.html", null ],
    [ "signalwire::rest::PaginatedIterator", "classsignalwire_1_1rest_1_1PaginatedIterator.html", null ],
    [ "signalwire::rest::RestClient::ProjectNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1ProjectNamespace.html", null ],
    [ "signalwire::rest::RestClient::ProjectTokens", "structsignalwire_1_1rest_1_1RestClient_1_1ProjectTokens.html", null ],
    [ "signalwire::pom::PromptObjectModel", "classsignalwire_1_1pom_1_1PromptObjectModel.html", null ],
    [ "signalwire::agent::Pronunciation", "structsignalwire_1_1agent_1_1Pronunciation.html", null ],
    [ "signalwire::rest::RestClient::PubSubNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1PubSubNamespace.html", null ],
    [ "signalwire::rest::RestClient::RegistryBrands", "structsignalwire_1_1rest_1_1RestClient_1_1RegistryBrands.html", null ],
    [ "signalwire::rest::RestClient::RegistryCampaigns", "structsignalwire_1_1rest_1_1RestClient_1_1RegistryCampaigns.html", null ],
    [ "signalwire::rest::RestClient::RegistryNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1RegistryNamespace.html", null ],
    [ "signalwire::rest::RestClient::RegistryNumbers", "structsignalwire_1_1rest_1_1RestClient_1_1RegistryNumbers.html", null ],
    [ "signalwire::rest::RestClient::RegistryOrders", "structsignalwire_1_1rest_1_1RestClient_1_1RegistryOrders.html", null ],
    [ "signalwire::relay::RelayClient", "classsignalwire_1_1relay_1_1RelayClient.html", null ],
    [ "signalwire::relay::RelayConfig", "structsignalwire_1_1relay_1_1RelayConfig.html", null ],
    [ "signalwire::relay::RelayEvent", "structsignalwire_1_1relay_1_1RelayEvent.html", [
      [ "signalwire::relay::CallEvent", "structsignalwire_1_1relay_1_1CallEvent.html", null ],
      [ "signalwire::relay::ComponentEvent", "structsignalwire_1_1relay_1_1ComponentEvent.html", null ],
      [ "signalwire::relay::DialEvent", "structsignalwire_1_1relay_1_1DialEvent.html", null ],
      [ "signalwire::relay::MessageEvent", "structsignalwire_1_1relay_1_1MessageEvent.html", null ]
    ] ],
    [ "signalwire::rest::RestClient::PhoneNumbersNamespace::RelayTopicOptions", "structsignalwire_1_1rest_1_1RestClient_1_1PhoneNumbersNamespace_1_1RelayTopicOptions.html", null ],
    [ "signalwire::rest::RestClient", "classsignalwire_1_1rest_1_1RestClient.html", null ],
    [ "std::runtime_error", null, [
      [ "signalwire::rest::SignalWireRestError", "classsignalwire_1_1rest_1_1SignalWireRestError.html", null ],
      [ "signalwire::utils::SchemaValidationError", "classsignalwire_1_1utils_1_1SchemaValidationError.html", null ]
    ] ],
    [ "signalwire::swml::Schema", "classsignalwire_1_1swml_1_1Schema.html", null ],
    [ "signalwire::utils::SchemaUtils", "classsignalwire_1_1utils_1_1SchemaUtils.html", null ],
    [ "signalwire::pom::Section", "classsignalwire_1_1pom_1_1Section.html", null ],
    [ "signalwire::swml::Section", "structsignalwire_1_1swml_1_1Section.html", null ],
    [ "signalwire::swml::Service", "classsignalwire_1_1swml_1_1Service.html", [
      [ "signalwire::agent::AgentBase", "classsignalwire_1_1agent_1_1AgentBase.html", [
        [ "signalwire::prefabs::ConciergeAgent", "classsignalwire_1_1prefabs_1_1ConciergeAgent.html", null ],
        [ "signalwire::prefabs::FAQBotAgent", "classsignalwire_1_1prefabs_1_1FAQBotAgent.html", null ],
        [ "signalwire::prefabs::InfoGathererAgent", "classsignalwire_1_1prefabs_1_1InfoGathererAgent.html", null ],
        [ "signalwire::prefabs::ReceptionistAgent", "classsignalwire_1_1prefabs_1_1ReceptionistAgent.html", null ],
        [ "signalwire::prefabs::SurveyAgent", "classsignalwire_1_1prefabs_1_1SurveyAgent.html", null ]
      ] ]
    ] ],
    [ "signalwire::security::SessionManager", "classsignalwire_1_1security_1_1SessionManager.html", null ],
    [ "signalwire::skills::SkillBase", "classsignalwire_1_1skills_1_1SkillBase.html", null ],
    [ "signalwire::skills::SkillHttpResponse", "structsignalwire_1_1skills_1_1SkillHttpResponse.html", null ],
    [ "signalwire::skills::SkillManager", "classsignalwire_1_1skills_1_1SkillManager.html", null ],
    [ "signalwire::skills::SkillPromptSection", "structsignalwire_1_1skills_1_1SkillPromptSection.html", null ],
    [ "signalwire::skills::SkillRegistry", "classsignalwire_1_1skills_1_1SkillRegistry.html", null ],
    [ "signalwire::contexts::Step", "classsignalwire_1_1contexts_1_1Step.html", null ],
    [ "signalwire::agent::SwaigQueryParam", "structsignalwire_1_1agent_1_1SwaigQueryParam.html", null ],
    [ "signalwire::swaig::ToolDefinition", "structsignalwire_1_1swaig_1_1ToolDefinition.html", null ],
    [ "signalwire::swml::Verb", "structsignalwire_1_1swml_1_1Verb.html", null ],
    [ "signalwire::swml::VerbDefinition", "structsignalwire_1_1swml_1_1VerbDefinition.html", null ],
    [ "signalwire::utils::VerbInfo", "structsignalwire_1_1utils_1_1VerbInfo.html", null ],
    [ "signalwire::rest::RestClient::VideoConferenceTokens", "structsignalwire_1_1rest_1_1RestClient_1_1VideoConferenceTokens.html", null ],
    [ "signalwire::rest::RestClient::VideoNamespace", "structsignalwire_1_1rest_1_1RestClient_1_1VideoNamespace.html", null ],
    [ "signalwire::rest::RestClient::VideoRoomRecordings", "structsignalwire_1_1rest_1_1RestClient_1_1VideoRoomRecordings.html", null ],
    [ "signalwire::rest::RestClient::VideoRoomSessions", "structsignalwire_1_1rest_1_1RestClient_1_1VideoRoomSessions.html", null ],
    [ "signalwire::rest::RestClient::VideoRoomTokens", "structsignalwire_1_1rest_1_1RestClient_1_1VideoRoomTokens.html", null ],
    [ "signalwire::rest::RestClient::VideoStreams", "structsignalwire_1_1rest_1_1RestClient_1_1VideoStreams.html", null ],
    [ "signalwire::security::WebhookValidatorOptions", "structsignalwire_1_1security_1_1WebhookValidatorOptions.html", null ],
    [ "signalwire::relay::WebSocketClient", "classsignalwire_1_1relay_1_1WebSocketClient.html", null ]
];